apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wikijs.fullname" . }}-config
  labels:
    {{- include "wikijs.labels" . | nindent 4 }}
stringData:
  config.yml: |
    {{- .Values.wikijs.config | toYaml | nindent 4 }}
