apiVersion: v1
kind: Service
metadata:
  name: {{ include "wikijs.fullname" . }}
  labels:
    {{- include "wikijs.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "wikijs.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
